name: Visual Regression

on: pull_request

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 期待値画像をbaseブランチのArtifactからダウンロードする
      - uses: dawidd6/action-download-artifact@v3
        with:
          name: screenshots # artifact名
          path: .reg/expected # ダウンロードしたArtifactsの展開先
          workflow: upload_expected_image.yaml # 画像をアップロードしているワークフローのファイル名
          branch: ${{ github.base_ref }}

      # 現在のブランチでスクリーンショット画像を取得する
      - name: Record current screenshots
        run: ./gradlew :app:recordRoborazziDemoAnswerDebug

      # reg-suitのインストールと実行
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install & Run reg-suit
        run: |
          npm install 
          npx reg-suit run

      # 結果をArtifactsにアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: visual-regression-results
          path: .reg