name: Visual Regression

on: pull_request

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 期待値画像をbaseブランチのArtifactからダウンロードする


      # 現在のブランチでスクリーンショット画像を取得する


      # reg-suitのインストールと実行


      # 結果をArtifactsにアップロード
